language: java
jdk:
  - openjdk11
services:
  - mysql
env:
  - MYSQL_USER=root
  - MYSQL_PWD=
before_install:
  - mysql -e "create database nachrichtenleicht_test;" --user=root
  - chmod +x gradlew
script:
  - ./gradlew test jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
