version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SENTRY_DSN=${SENTRY_DSN}
    networks:
      - nachrichtenleicht
  mysql:
    image: "mysql:8"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=nachrichtenleicht
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - nachrichtenleicht-db:/var/lib/mysql
      - nachrichtenleicht-db-config:/etc/mysql/conf.d
    networks:
      - nachrichtenleicht
volumes:
  nachrichtenleicht-db:
  nachrichtenleicht-db-config:
networks:
  nachrichtenleicht:
